### ISSUE TITLE
No module named '_swigfaiss' !?

### ISSUE THREAD

**Issue by fouadb66** [onfido/faiss_prebuilt#4]
getting this error after installing prebuild faiss 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/faiss/__init__.py", line 28, in <module>
    from .swigfaiss import *
  File "/usr/local/lib/python3.5/dist-packages/faiss/swigfaiss.py", line 17, in <module>
    _swigfaiss = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/faiss/swigfaiss.py", line 16, in swig_import_helper
    return importlib.import_module('_swigfaiss')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_swigfaiss'

**Comment by orf** [comment]
What operating system are you using, and version?

**Comment by orf** [comment]
This should now be fixed, please use the new package name `faiss` instead of `faiss_prebuilt`
